version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - cluster_network

  kafka:
    image: lucienfregosi/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cluster_network
    deploy:
      mode: replicated
      replicas: 3
  
  schema-registry:
     image: confluentinc/cp-schema-registry:latest
     depends_on:
       - zookeeper
       - kafka
     environment:
       SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
       SCHEMA_REGISTRY_HOST_NAME: schema-registry
     ports:
      - "8081:8081"
     networks:
      - cluster_network

  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: zookeeper:2181
      RP_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
      - cluster_network

  elasticsearch:
    image: lucienfregosi/elasticsearch-configured:v3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      CLUSTER_NAME : "elasticsearch"
      NODE_NAME : "elasticsearch"
      PUBLISH_HOST : 217.182.141.128
    volumes:
      - /data/es
    networks:
      - cluster_network

  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - cluster_network
  
  spark-master:
    image: singularities/spark
    command: start-spark master
    ports:
      - 6066:6066
      - 7070:7070
      - 8090:8090
      - 50070:50070
    networks:
      - cluster_network


  spark-slave:
    image: singularities/spark
    command: start-spark worker spark-master
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    depends_on:
     - spark-master
    networks:
      - cluster_network



networks:
  cluster_network:
      external: true

volumes:
  elasticdata:
